### PR TITLE
Add plausible analytics to home page

### PR DESCRIPTION
**Pull request by MridulS**

### CODE REVIEW

**Review by dschult — APPROVED** [review]
I don't know any good way to test that this will do what we want it to do. So, I'm approving it and we'll watch to see what happens...  Is this a reasonable approach?

**Comment by MridulS** [comment]
Yes, anyway we need to do a manual build and push after this to networkx/networkx.github.io which hosts the raw github pages deployment. I can do that after merging this

**Comment by MridulS** [comment]
I'll go ahead and self merge this one and see if everything works.

If this works fine, we can also add plausible to our docs.

**Comment by MridulS** [comment]
Looks like its working :)

Screenshot 2023-02-07 at 12 22 57 AM

**Pull request merged**
